services:
  droos_bot:
    build:
      context: ./
      dockerfile: Dockerfile
      args:
        UID: ${UID:-1000}
        GID: ${GID:-1000}
    working_dir: /app
    command: ['uv', 'run', 'python', '-m', 'droos_bot']
    environment:
      - TZ=Africa/Cairo
    restart: unless-stopped
    volumes:
      - './:/app'
      - '/etc/localtime:/etc/localtime:ro'
