services:
  droos_bot:
    build:
      context: ./
      dockerfile: Dockerfile
    command: bash -c "cd app && python3 -m droos_bot"
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Africa/Cairo
      - /etc/localtime:/etc/localtime:ro
    restart: unless-stopped
    volumes:
      - "./:/app/app"
